# Generated by Django 5.1.1 on 2024-10-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': 'prefectures(都道府県)',
                'db_table': 'prefectures',
            },
        ),
        migrations.CreateModel(
            name='StoreArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefecture_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_in_prefecture', to='store.prefecture')),
            ],
            options={
                'verbose_name': '店舗エリア',
                'verbose_name_plural': 'store_areas(店舗エリア)',
                'db_table': 'store_areas',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_in_area', to='store.storearea')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': 'stores(店舗)',
                'db_table': 'stores',
            },
        ),
    ]
