# Generated by Django 5.1.1 on 2024-10-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_prefecture_is_active_storearea_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storearea',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
