# Generated by Django 5.1.1 on 2024-10-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_storearea_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storearea',
            old_name='order_no',
            new_name='display_order',
        ),
    ]
