# Generated by Django 5.1.1 on 2024-10-15 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0004_alter_clothes_sex'),
        ('store', '0003_alter_storearea_order_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedClothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clothes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for_users', to='clothes.clothes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_clothes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedStores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for_users', to='store.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
