# Generated by Django 5.1.1 on 2024-10-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedclothes',
            options={'verbose_name': 'おすすめ商品', 'verbose_name_plural': 'recommended_clothes(おすすめ商品)'},
        ),
        migrations.AlterModelOptions(
            name='recommendedstores',
            options={'verbose_name': 'おすすめ店舗', 'verbose_name_plural': 'recommended_stores(おすすめ店舗)'},
        ),
        migrations.AlterModelTable(
            name='recommendedclothes',
            table='recommended_clothes',
        ),
        migrations.AlterModelTable(
            name='recommendedstores',
            table='recommended_stores',
        ),
    ]
