# Generated by Django 5.1.1 on 2024-10-15 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_rename_order_no_clothescategory_display_order'),
        ('recommendation', '0002_alter_recommendedclothes_options_and_more'),
        ('store', '0004_rename_order_no_storearea_display_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedclothes',
            name='clothes_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for_users', to='clothes.clothes'),
        ),
        migrations.AlterField(
            model_name='recommendedclothes',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_clothes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendedstores',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for_users', to='store.store'),
        ),
        migrations.AlterField(
            model_name='recommendedstores',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
