# Generated by Django 5.1.1 on 2024-10-15 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_rename_order_no_clothescategory_display_order'),
        ('store', '0004_rename_order_no_storearea_display_order'),
        ('user', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteClothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_STOCK', 'IN STOCK'), ('SOLD_OUT', 'SOLD OUT')], default='IN_STOCK', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clothes_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='clothes.clothes')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clothes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'お気に入り商品',
                'verbose_name_plural': 'favorite_clothes(お気に入り商品)',
                'db_table': 'favorite_clothes',
            },
        ),
        migrations.CreateModel(
            name='FavoriteStores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='store.store')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'お気に入り店舗',
                'verbose_name_plural': 'favorite_stores(お気に入り店舗)',
                'db_table': 'favorite_stores',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_term', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '検索履歴',
                'verbose_name_plural': 'search_histories(検索履歴)',
                'db_table': 'search_histories',
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clothes_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='clothes.clothes')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '閲覧履歴',
                'verbose_name_plural': 'view_histories(閲覧履歴)',
                'db_table': 'view_histories',
            },
        ),
    ]
