# Generated by Django 5.1.1 on 2024-10-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_favoriteclothes_favoritestores_searchhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
