# Generated by Django 5.1.1 on 2024-10-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_prefecture_is_active_storearea_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '商品ブランド',
                'verbose_name_plural': 'clothes_brands(商品ブランド)',
                'db_table': 'clothes_brands',
            },
        ),
        migrations.CreateModel(
            name='ClothesCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='clothes.clothescategory')),
            ],
            options={
                'verbose_name': '商品カテゴリ',
                'verbose_name_plural': 'clothes_categories(商品カテゴリ)',
                'db_table': 'clothes_categories',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_clothes_id', models.CharField(max_length=255, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('', '---------'), ('M', '男性'), ('F', '女性'), ('U', 'ユニセックス')], max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes_in_store', to='store.store')),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes_in_brand', to='clothes.clothesbrand')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes_in_category', to='clothes.clothescategory')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': 'clothes(商品)',
                'db_table': 'clothes',
            },
        ),
    ]
