# Generated by Django 5.1.1 on 2024-10-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothescategory_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothescategory',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
