# Generated by Django 5.1.1 on 2024-10-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_clothescategory_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---------'), ('M', 'MENS'), ('F', 'LADIES'), ('U', 'MENS/LADIES')], max_length=1),
        ),
    ]
