# Generated by Django 5.1.1 on 2024-10-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_clothes_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothescategory',
            old_name='order_no',
            new_name='display_order',
        ),
    ]
