# Generated by Django 5.1.1 on 2024-10-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_alter_clothes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '-'), ('M', 'MENS'), ('F', 'LADIES'), ('U', 'MENS/LADIES')], max_length=1),
        ),
    ]
