# Generated by Django 5.1.1 on 2024-10-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
