# Generated by Django 5.1.1 on 2024-10-24 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_banner_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'トピック', 'verbose_name_plural': 'topics(トピック)'},
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
